---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kumbi
resources: [../../base, secrets.yaml]
images:
  - name: kumbi/backend
    newName: kumbi/backend
    newTag: dev
  - name: kumbi/frontend
    newName: kumbi/frontend
    newTag: dev
patches:
  - patch: |-
      - op: replace
        path: /data/ENV
        value: development
    target:
      kind: ConfigMap
      name: backend-config
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          envoy.gateway.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "selfsigned-issuer"
      - op: replace
        path: /spec/listeners/0/hostname
        value: kumbi.local
      - op: add
        path: /spec/listeners/0/tls
        value:
          certificateRef:
            group: gateway.networking.k8s.io
            kind: Certificate
            name: kumbi-tls-cert
    target:
      kind: Gateway
      name: kumbi-gateway
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment
      name: frontend
  - patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/imagePullPolicy
        value: IfNotPresent
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Job
      name: seed-admin
