---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kumbi-prod
resources: [../../base, secrets.yaml]
images:
  - name: kumbi/backend
    newName: kumbi/backend
    newTag: prod
  - name: kumbi/frontend
    newName: kumbi/frontend
    newTag: prod
patches:
  - patch: |-
      - op: replace
        path: /spec/listeners/0/addresses
        value:
          - type: IPAddress
            value: 10.0.0.200
      - op: replace
        path: /spec/listeners/0/hostname
        value: kumbike.org
      - op: add
        path: /metadata/annotations
        value:
          envoy.gateway.kubernetes.io/ssl-redirect: "false"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
    target:
      kind: Gateway
      name: kumbi-gateway
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment
      name: frontend
  - patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/imagePullPolicy
        value: IfNotPresent
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Job
      name: seed-admin
