---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - issuer.yaml
  - ingress.yaml
  - secrets.yaml

images:
  - name: kumbi/backend
    newName: ${REGISTRY}/kumbi/backend
    newTag: ${TAG}
  - name: kumbi/frontend
    newName: ${REGISTRY}/kumbi/frontend
    newTag: ${TAG}

# Ensure secrets are applied
secretsGenerator:
  - name: kumbi-secrets
    envs:
      - secrets.env
