export interface Country {
  name: string
  iso: string // ISO 3166-1 alpha-2
  callingCode: string // without the leading '+'
}

// Curated list of UN-recognised countries. Flag emoji is derived from the ISO
// code at runtime (see flagEmoji) so it is always correct.
export const countries: Country[] = [
  { name: 'Kenya', iso: 'KE', callingCode: '254' },
  { name: 'Uganda', iso: 'UG', callingCode: '256' },
  { name: 'Tanzania', iso: 'TZ', callingCode: '255' },
  { name: 'Rwanda', iso: 'RW', callingCode: '250' },
  { name: 'Burundi', iso: 'BI', callingCode: '257' },
  { name: 'South Sudan', iso: 'SS', callingCode: '211' },
  { name: 'Ethiopia', iso: 'ET', callingCode: '251' },
  { name: 'Somalia', iso: 'SO', callingCode: '252' },
  { name: 'Eritrea', iso: 'ER', callingCode: '291' },
  { name: 'Djibouti', iso: 'DJ', callingCode: '253' },
  { name: 'Sudan', iso: 'SD', callingCode: '249' },
  { name: 'Egypt', iso: 'EG', callingCode: '20' },
  { name: 'Libya', iso: 'LY', callingCode: '218' },
  { name: 'Tunisia', iso: 'TN', callingCode: '216' },
  { name: 'Algeria', iso: 'DZ', callingCode: '213' },
  { name: 'Morocco', iso: 'MA', callingCode: '212' },
  { name: 'Mauritania', iso: 'MR', callingCode: '222' },
  { name: 'Senegal', iso: 'SN', callingCode: '221' },
  { name: 'Mali', iso: 'ML', callingCode: '223' },
  { name: 'Guinea', iso: 'GN', callingCode: '224' },
  { name: 'Côte d’Ivoire', iso: 'CI', callingCode: '225' },
  { name: 'Burkina Faso', iso: 'BF', callingCode: '226' },
  { name: 'Ghana', iso: 'GH', callingCode: '233' },
  { name: 'Togo', iso: 'TG', callingCode: '228' },
  { name: 'Benin', iso: 'BJ', callingCode: '229' },
  { name: 'Nigeria', iso: 'NG', callingCode: '234' },
  { name: 'Niger', iso: 'NE', callingCode: '227' },
  { name: 'Chad', iso: 'TD', callingCode: '235' },
  { name: 'Cameroon', iso: 'CM', callingCode: '237' },
  { name: 'Central African Republic', iso: 'CF', callingCode: '236' },
  { name: 'Gabon', iso: 'GA', callingCode: '241' },
  { name: 'Congo', iso: 'CG', callingCode: '242' },
  { name: 'Democratic Republic of the Congo', iso: 'CD', callingCode: '243' },
  { name: 'Angola', iso: 'AO', callingCode: '244' },
  { name: 'Zambia', iso: 'ZM', callingCode: '260' },
  { name: 'Zimbabwe', iso: 'ZW', callingCode: '263' },
  { name: 'Malawi', iso: 'MW', callingCode: '265' },
  { name: 'Mozambique', iso: 'MZ', callingCode: '258' },
  { name: 'South Africa', iso: 'ZA', callingCode: '27' },
  { name: 'Botswana', iso: 'BW', callingCode: '267' },
  { name: 'Namibia', iso: 'NA', callingCode: '264' },
  { name: 'Lesotho', iso: 'LS', callingCode: '266' },
  { name: 'Eswatini', iso: 'SZ', callingCode: '268' },
  { name: 'Madagascar', iso: 'MG', callingCode: '261' },
  { name: 'Mauritius', iso: 'MU', callingCode: '230' },
  { name: 'Seychelles', iso: 'SC', callingCode: '248' },
  { name: 'United States', iso: 'US', callingCode: '1' },
  { name: 'Canada', iso: 'CA', callingCode: '1' },
  { name: 'Mexico', iso: 'MX', callingCode: '52' },
  { name: 'Brazil', iso: 'BR', callingCode: '55' },
  { name: 'Argentina', iso: 'AR', callingCode: '54' },
  { name: 'Chile', iso: 'CL', callingCode: '56' },
  { name: 'Colombia', iso: 'CO', callingCode: '57' },
  { name: 'Peru', iso: 'PE', callingCode: '51' },
  { name: 'United Kingdom', iso: 'GB', callingCode: '44' },
  { name: 'Ireland', iso: 'IE', callingCode: '353' },
  { name: 'France', iso: 'FR', callingCode: '33' },
  { name: 'Germany', iso: 'DE', callingCode: '49' },
  { name: 'Netherlands', iso: 'NL', callingCode: '31' },
  { name: 'Belgium', iso: 'BE', callingCode: '32' },
  { name: 'Switzerland', iso: 'CH', callingCode: '41' },
  { name: 'Italy', iso: 'IT', callingCode: '39' },
  { name: 'Spain', iso: 'ES', callingCode: '34' },
  { name: 'Portugal', iso: 'PT', callingCode: '351' },
  { name: 'Sweden', iso: 'SE', callingCode: '46' },
  { name: 'Norway', iso: 'NO', callingCode: '47' },
  { name: 'Denmark', iso: 'DK', callingCode: '45' },
  { name: 'Finland', iso: 'FI', callingCode: '358' },
  { name: 'Poland', iso: 'PL', callingCode: '48' },
  { name: 'Russia', iso: 'RU', callingCode: '7' },
  { name: 'Ukraine', iso: 'UA', callingCode: '380' },
  { name: 'Turkey', iso: 'TR', callingCode: '90' },
  { name: 'Greece', iso: 'GR', callingCode: '30' },
  { name: 'India', iso: 'IN', callingCode: '91' },
  { name: 'Pakistan', iso: 'PK', callingCode: '92' },
  { name: 'Bangladesh', iso: 'BD', callingCode: '880' },
  { name: 'China', iso: 'CN', callingCode: '86' },
  { name: 'Japan', iso: 'JP', callingCode: '81' },
  { name: 'South Korea', iso: 'KR', callingCode: '82' },
  { name: 'Indonesia', iso: 'ID', callingCode: '62' },
  { name: 'Malaysia', iso: 'MY', callingCode: '60' },
  { name: 'Singapore', iso: 'SG', callingCode: '65' },
  { name: 'Philippines', iso: 'PH', callingCode: '63' },
  { name: 'Thailand', iso: 'TH', callingCode: '66' },
  { name: 'Vietnam', iso: 'VN', callingCode: '84' },
  { name: 'Australia', iso: 'AU', callingCode: '61' },
  { name: 'New Zealand', iso: 'NZ', callingCode: '64' },
  { name: 'United Arab Emirates', iso: 'AE', callingCode: '971' },
  { name: 'Saudi Arabia', iso: 'SA', callingCode: '966' },
  { name: 'Qatar', iso: 'QA', callingCode: '974' },
  { name: 'Kuwait', iso: 'KW', callingCode: '965' },
  { name: 'Israel', iso: 'IL', callingCode: '972' },
  { name: 'Jordan', iso: 'JO', callingCode: '962' },
  { name: 'Lebanon', iso: 'LB', callingCode: '961' },
  { name: 'Afghanistan', iso: 'AF', callingCode: '93' },
  { name: 'Nepal', iso: 'NP', callingCode: '977' },
  { name: 'Sri Lanka', iso: 'LK', callingCode: '94' },
  { name: 'Iran', iso: 'IR', callingCode: '98' },
  { name: 'Iraq', iso: 'IQ', callingCode: '964' },
  { name: 'Kazakhstan', iso: 'KZ', callingCode: '7' },
  { name: 'South Sudan', iso: 'SS', callingCode: '211' },
  { name: 'Cuba', iso: 'CU', callingCode: '53' },
  { name: 'Jamaica', iso: 'JM', callingCode: '1876' },
  { name: 'Kenya', iso: 'KE', callingCode: '254' },
]

export function flagEmoji(iso: string): string {
  if (!iso) return '🏳️'
  return iso
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
}

export function findCountry(iso: string): Country | undefined {
  return countries.find((c) => c.iso === iso)
}
